version: "3.9"
services:
  umami-postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    user: postgres
    env_file:
      - umami.env
    volumes:
      - umami-pg:/var/lib/postgresql/data
    ports:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ge
  umami:
    image: ghcr.io/umami-software/umami:postgresql-v2.9.0
    ports:
      - 3000
    env_file:
      - umami.env
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      caddy: analytics.grassecon.net
      caddy.reverse_proxy: "{{upstreams 3000}}"
    restart: unless-stopped
    depends_on:
      umami-postgres:
        condition: service_healthy    
    networks:
      - ge

networks:
  ge:
    external: true

volumes:
  umami-pg:
    driver: local