version: '3.9'

services:
  git:
    image: gitea/gitea:1.17.1
    container_name: gitea
    restart: unless-stopped
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - ./gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitea.rule=Host(`git.grassecon.net`)
      - traefik.http.routers.gitea.service=gitea-server
      - traefik.http.services.gitea-server.loadbalancer.server.port=3000
      - traefik.http.routers.gitea.tls=true
      - traefik.http.routers.gitea.tls.certresolver=le
    expose:
      - '3000'
      - '22'
    ports:
      - '22:22'
    networks:
      - traefik_ge         

networks:
  traefik_ge:
    external: true