version: "3.9"
services:
  gitea:
    image: gitea/gitea:1.21.4
    ports:
      - 3000
      - 22:22
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      caddy: git.grassecon.net
      caddy.reverse_proxy: "{{upstreams 3000}}"
    restart: unless-stopped
    networks:
      - ge

networks:
  ge:
    external: true

volumes:
  gitea-data:
    driver: local