version: '3.9'

services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - './mariadb-data:/var/lib/mysql'
    expose:
      - '3306'
    ports:
      - '127.0.0.1:3306:3306'      
    env_file:
      - .env
    networks:
      - traefik_ge

networks:
  traefik_ge:
    external: true