version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: unless-stopped
    volumes:
      - './pg-data:/var/lib/postgresql/data'
    expose:
      - '5432'
    ports:
      - '127.0.0.1:5432:5432'
    env_file:
      - .env
    networks:
      - traefik_ge

networks:
  traefik_ge:
    external: true