version: '3.9'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server --save 120 1 --loglevel warning
    volumes:
      - './redis-data:/data'
    expose:
      - '6379'
    ports:
      - '127.0.0.1:6379:6379' 
    networks:
      - traefik_ge   

networks:
  traefik_ge:
    external: true